ask_openai:
  name: Ask OpenAI for Song Info
  description: Get Song Details in different flavors from OpenAI
  fields:
    song_title:
      name: Song Title
      description: Song Title
      example: "Seven Nation Army"
      required: false
      selector: 
        text:
    song_artist:
      name: Song Artist
      description: Song Artist
      example: "The White Stripes"
      required: false
      selector: 
        text:
    prompt:
      name: Prompt
      description: Prompt
      example: "General Song Info"
      required: false
      selector:
        select:
          options:
            - label: General Song Info
              value: "General Song Info"
            - label: Lyric Meanings
              value: "Lyric Meanings"
            - label: Recording Info
              value: "Recording Info"
            - label: Song Trivia
              value: "Song Trivia"
            - label: Songwriters
              value: "Songwriters"
            - label: Similar Songs
              value: "Similar Songs"
    personality:
      name: Personality
      description: Personality of the response
      example: "Musician"
      required: false
      selector:
        select:
          options:
            - label: Canadian
              value: "Canadian"
            - label: Clueless
              value: "Clueless"
            - label: Country Bumpkin
              value: "Country Bumpkin"
            - label: Grumpy Old Man
              value: "Grumpy Old Man"
            - label: Hippie
              value: "Hippie"
            - label: Hipster
              value: "Hipster"
            - label: Intellectual
              value: "Intellectual"
            - label: Karen
              value: "Karen"
            - label: Hyperbole
              value: "Hyperbole"
            - label: Musician
              value: "Musician"
            - label: Normal
              value: "Normal"
            - label: Old English
              value: "Old English"
            - label: Paranoid
              value: "Paranoid"
            - label: Pirate
              value: "Pirate"
            - label: Redneck
              value: "Redneck"
            - label: Scientist
              value: "Scientist"
            - label: Stoner
              value: "Stoner"
            - label: Superhero
              value: "Superhero"
            - label: Valley Girl
              value: "Valley Girl"
get_openai_image:
  name: Create OpenAI Image
  description: Create an image using a prompt
  fields:
    song_title:
      name: Song Title
      description: Song Title
      example: "Freebird"
      required: false
      selector: 
        text:
    song_artist:
      name: Song Artist
      description: Song Artist
      example: "Lynyrd Skynyrd"
      required: false
      selector: 
        text:
    image_type:
      name: Image Type
      description: Image Type
      example: "Gothic"
      required: false
      selector:
        select:
          options:
            - label: Abstract Expressionist
              value: "Abstract Expressionist"
            - label: Album Cover
              value: "Album Cover"
            - label: Andy Warhol
              value: "Andy Warhol"
            - label: Anime
              value: "Anime"
            - label: Antebellum
              value: "Antebellum"
            - label: Black and White
              value: "Black and White"
            - label: Cartoon
              value: "Cartoon"
            - label: Collage
              value: "Collage"
            - label: Comic Book
              value: "Comic Book"
            - label: Cyberpunk
              value: "Cyberpunk"
            - label: Frida Kahlo
              value: "Frida Kahlo"
            - label: Futurism
              value: "Futurism"
            - label: Gothic
              value: "Gothic"
            - label: Hyperrealism
              value: "Hyperrealism"
            - label: Humorous
              value: "Humorous"
            - label: Landscape
              value: "Landscape"
            - label: Metaphysical
              value: "Metaphysical"
            - label: Minimalism
              value: "Minimalism"
            - label: Modern
              value: "Modern"
            - label: Neon
              value: "Neon"
            - label: Normal
              value: "Normal"
            - label: Old Cartoon
              value: "Old Cartoon"
            - label: Oil Painting
              value: "Oil Painting"
            - label: Pablo Picasso
              value: "Pablo Picasso"
            - label: Pastel
              value: "Pastel"
            - label: Photorealism
              value: "Photorealism"
            - label: Psychedelic
              value: "Psychedelic"
            - label: Salvador Dalí
              value: "Salvador Dalí"
            - label: Steampunk
              value: "Steampunk"
            - label: Still Life
              value: "Still Life"
            - label: Tim Burton
              value: "Tim Burton"
            - label: Van Gogh
              value: "Van Gogh"
            - label: Vintage
              value: "Vintage"
            - label: Watercolors
              value: "Watercolors"
            - label: Whimsical
              value: "Whimdsical"
            - label: Yayoi Kusama
              value: "Yayoi Kusama"
