ask_openai:
  name: Ask OpenAI for Song Info
  description: Get Song Details in different flavors from OpenAI
  fields:
    song_title:
      name: Song Title
      description: Song Title
      example: "Seven Nation Army"
      required: false
      selector:
        text:
    song_artist:
      name: Song Artist
      description: Song Artist
      example: "The White Stripes"
      required: false
      selector:
        text:
    prompt:
      name: Prompt
      description: Prompt
      example: "General Song Info"
      required: false
      selector:
        select:
          options:
            - label: General Song Info
              value: "General Song Info"
            - label: Artist Info
              value: "Artist Info"
            - label: Lyric Meanings
              value: "Lyric Meanings"
            - label: Recording Info
              value: "Recording Info"
            - label: Song Trivia
              value: "Song Trivia"
            - label: Songwriters
              value: "Songwriters"
            - label: Similar Songs
              value: "Similar Songs"
    personality:
      name: Personality
      description: Personality of the response
      example: "Musician"
      required: false
      selector:
        select:
          options:
            - label: Boring
              value: "Boring"
            - label: Canadian
              value: "Canadian"
            - label: Clueless
              value: "Clueless"
            - label: Country Bumpkin
              value: "Country Bumpkin"
            - label: Grumpy Old Man
              value: "Grumpy Old Man"
            - label: Hippie
              value: "Hippie"
            - label: Hipster
              value: "Hipster"
            - label: Intellectual
              value: "Intellectual"
            - label: Journalist
              value: "Journalist"
            - label: Karen
              value: "Karen"
            - label: Hyperbole
              value: "Hyperbole"
            - label: Musician
              value: "Musician"
            - label: Mythologist
              value: "Mythologist"
            - label: Normal
              value: "Normal"
            - label: Nostalgic
              value: "Nostalgic"
            - label: Old English
              value: "Old English"
            - label: Paranoid
              value: "Paranoid"
            - label: Pirate
              value: "Pirate"
            - label: Redneck
              value: "Redneck"
            - label: Romantic
              value: "Romantic"
            - label: Scientist
              value: "Scientist"
            - label: Stoner
              value: "Stoner"
            - label: Superhero
              value: "Superhero"
            - label: Valley Girl
              value: "Valley Girl"
ask_openai_secondary:
  name: Ask OpenAI for Song Info (Secondary)
  description: Get Song Details in different flavors from OpenAI
  fields:
    song_title:
      name: Song Title
      description: Song Title
      example: "Seven Nation Army"
      required: false
      selector:
        text:
    song_artist:
      name: Song Artist
      description: Song Artist
      example: "The White Stripes"
      required: false
      selector:
        text:
    prompt:
      name: Prompt
      description: Prompt
      example: "General Song Info"
      required: false
      selector:
        select:
          options:
            - label: General Song Info
              value: "General Song Info"
            - label: Artist Info
              value: "Artist Info"
            - label: Lyric Meanings
              value: "Lyric Meanings"
            - label: Recording Info
              value: "Recording Info"
            - label: Song Trivia
              value: "Song Trivia"
            - label: Songwriters
              value: "Songwriters"
            - label: Similar Songs
              value: "Similar Songs"
    personality:
      name: Personality
      description: Personality of the response
      example: "Musician"
      required: false
      selector:
        select:
          options:
            - label: Boring
              value: "Boring"
            - label: Canadian
              value: "Canadian"
            - label: Clueless
              value: "Clueless"
            - label: Country Bumpkin
              value: "Country Bumpkin"
            - label: Grumpy Old Man
              value: "Grumpy Old Man"
            - label: Hippie
              value: "Hippie"
            - label: Hipster
              value: "Hipster"
            - label: Intellectual
              value: "Intellectual"
            - label: Journalist
              value: "Journalist"
            - label: Karen
              value: "Karen"
            - label: Hyperbole
              value: "Hyperbole"
            - label: Musician
              value: "Musician"
            - label: Mythologist
              value: "Mythologist"
            - label: Normal
              value: "Normal"
            - label: Nostalgic
              value: "Nostalgic"
            - label: Old English
              value: "Old English"
            - label: Paranoid
              value: "Paranoid"
            - label: Pirate
              value: "Pirate"
            - label: Redneck
              value: "Redneck"
            - label: Romantic
              value: "Romantic"
            - label: Scientist
              value: "Scientist"
            - label: Stoner
              value: "Stoner"
            - label: Superhero
              value: "Superhero"
            - label: Valley Girl
              value: "Valley Girl"
get_openai_image:
  name: Create OpenAI Image
  description: Create an image using a prompt
  fields:
    song_title:
      name: Song Title
      description: Song Title
      example: "Freebird"
      required: false
      selector:
        text:
    song_artist:
      name: Song Artist
      description: Song Artist
      example: "Lynyrd Skynyrd"
      required: false
      selector:
        text:
    image_type:
      name: Image Type
      description: Image Type
      example: "Gothic"
      required: false
      selector:
        select:
          options:
            - label: Abstract Expressionist
              value: "abstract expressionist"
            - label: Absurd
              value: "ridiculous absurdist photo"
            - label: Absurd Cartoon
              value: "ridiculous absurdist cartoon"
            - label: Album Cover
              value: "album cover"
            - label: Andy Warhol
              value: "Andy Warhol"
            - label: Anime
              value: "modern anime"
            - label: Antebellum
              value: "Antebellum"
            - label: Avant-garde
              value: "Avant-garde"
            - label: Baroque
              value: "baroque"
            - label: Black and White
              value: "black and white photograph"
            - label: British Cartoon
              value: "british cartoon"
            - label: Cartoon
              value: "cartoon"
            - label: Collage
              value: "collage"
            - label: Comic Book
              value: "comic book cover"
            - label: Constructivism
              value: "constructivism"
            - label: Cyberpunk
              value: "cyberpunk"
            - label: Depressive
              value: "contemporary depressive realism"
            - label: Digital Art
              value: "digital art"
            - label: Dogs
              value: "dogs"
            - label: Dragon Art
              value: "dragon art"
            - label: Fantasy
              value: "fantasy art"
            - label: Fun
              value: "fun"
            - label: Futurism
              value: "futurism"
            - label: Geometric
              value: "geometric"
            - label: Gothic
              value: "gothic"
            - label: Graffiti
              value: "graffiti art"
            - label: Harlem Renaissance
              value: "Harlem renaissance"
            - label: Hyperrealism
              value: "hyperrealism"
            - label: Humorous
              value: "humorous"
            - label: Landscape
              value: "non-cartoon natural landscape"
            - label: Line Art
              value: "line art"
            - label: Literal
              value: "literal"
            - label: Lofi
              value: "lofi"
            - label: Marble Art
              value: "marble art"
            - label: Metaphysical
              value: "metaphysical"
            - label: Minimalism
              value: "minimalism"
            - label: Modern
              value: "modern"
            - label: Neon
              value: "neon colors"
            - label: Normal
              value: "Typical"
            - label: Old Cartoon
              value: "old timey cartoon"
            - label: Oil Painting
              value: "oil painting"
            - label: Pablo Picasso
              value: "Pablo Picasso"
            - label: Painterly
              value: "painterly"
            - label: Pastel
              value: "bright pastel colors"
            - label: Performance Art
              value: "performance art"
            - label: Photographic
              value: "realistic photographic"
            - label: Photorealism
              value: "photorealism"
            - label: Pointillist
              value: "pointillist"
            - label: Pop Surrealism
              value: "pop surrealism"
            - label: Psychedelic
              value: "psychedelic"
            - label: Retro
              value: "retro aesthetic"
            - label: Romantic
              value: "romantic"
            - label: Salvador Dalí
              value: "Salvador Dalí"
            - label: Stained Glass
              value: "stained glass"
            - label: Steampunk
              value: "steampunk"
            - label: Still Life
              value: "still life"
            - label: Thought Provoking
              value: "thought provoking"
            - label: Tilt-Shift
              value: "Tilt-Shift"
            - label: Tim Burton
              value: "Tim Burton"
            - label: Urban
              value: "urban"
            - label: Van Gogh
              value: "Van Gogh"
            - label: Vintage
              value: "vintage sepia toned photograph"
            - label: Watercolors
              value: "watercolors"
            - label: Whimsical
              value: "whimsical"
