ask_openai:
  name: Ask OpenAI for Song Info
  description: Get Song Details in different flavors from OpenAI
  fields:
    song_title:
      name: Song Title
      description: Song Title
      example: "Ball and Biscuit"
      required: false
      selector: 
        text:
    song_artist:
      name: Song Artist
      description: Song Artist
      example: "The White Stripes"
      required: false
      selector: 
        text:
    prompt:
      name: Prompt
      description: Prompt
      example: "Give me info about the song"
      required: false
      selector:
        select:
          options:
            - label: General Song Info
              value: "General Song Info"
            - label: Lyric Meanings
              value: "Lyric Meanings"
            - label: Recording Info
              value: "Recording Info"
            - label: Song Trivia
              value: "Song Trivia"
            - label: Songwriters
              value: "Songwriters"
            - label: Similar Songs
              value: "Similar Songs"
    personality:
      name: Personality
      description: Personality of the response
      example: "Record Producer"
      required: false
      selector:
        select:
          options:
            - label: Canadian
              value: "Canadian"
            - label: Clueless
              value: "Clueless"
            - label: Grumpy Old Man
              value: "Grumpy Old Man"
            - label: Hipster
              value: "Hipster"
            - label: Intellectual
              value: "Intellectual"
            - label: Karen
              value: "Karen"
            - label: Hyperbole
              value: "Hyperbole"
            - label: Musician
              value: "Musician"
            - label: Normal
              value: "Normal"
            - label: Old English
              value: "Old English"
            - label: Paranoid
              value: "Paranoid"
            - label: Pirate
              value: "Pirate"
            - label: Scientist
              value: "Scientist"
            - label: Stoner
              value: "Stoner"
            - label: Superhero
              value: "Superhero"
            - label: Valley Girl
              value: "Valley Girl"
get_openai_image:
  name: Create OpenAI Image
  description: Create an image using a prompt
  fields:
    song_title:
      name: Song Title
      description: Song Title
      example: "Ball and Biscuit"
      required: false
      selector: 
        text:
    song_artist:
      name: Song Artist
      description: Song Artist
      example: "The White Stripes"
      required: false
      selector: 
        text:
    image_type:
      name: Image Type
      description: Image Type
      example: "Andy Warhol"
      required: false
      selector:
        select:
          options:
            - label: Abstract Expressionist
              value: "abstract expressionist style"
            - label: Album Cover
              value: "album cover style"
            - label: Andy Warhol
              value: "Andy Warhol style"
            - label: Cartoon
              value: "cartoon"
            - label: Comic Book
              value: "comic book cover style"
            - label: Frida Kahlo
              value: "Frida Kahlo style"
            - label: Futurism
              value: "futurism style"
            - label: Gothic
              value: "gothic style"
            - label: Hyperrealism
              value: "hyperrealism style"
            - label: Humorous
              value: "humorous"
            - label: Landscape
              value: "landscape style"
            - label: Metaphysical
              value: "metaphysical style"
            - label: Minimalism
              value: "minimalism style"
            - label: Modern
              value: "modern style"
            - label: Normal
              value: "Normal"
            - label: Old Cartoon
              value: "Old cartoon style"
            - label: Oil Painting
              value: "oil painting style"
            - label: Pablo Picasso
              value: "Pablo Picasso style"
            - label: Pastel
              value: "pastel style"
            - label: Photorealism
              value: "photorealism style"
            - label: Psychedelic
              value: "psychedelic style"
            - label: Salvador Dalí
              value: "Salvador Dalí style"
            - label: Still Life
              value: "still life style"
            - label: Tim Burton
              value: "Tim Burton style"
            - label: Van Gogh
              value: "Van Gogh style"
            - label: Yayoi Kusama
              value: "Yayoi Kusama style"